name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [18.16.0]

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Check Npm -v
        run: npm -v

      - name: create env file
        working-directory: ./
        run: |
          pwd
          touch .env
          echo DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} >> .env
          echo clientId=${{ secrets.clientId }} >> .env
          cat .env

      - name: install dpendencies
        working-directory: ./
        run: |
          npm ci

      - name: run test
        working-directory: ./
        run: |
          npm run test
          
      - name: zip create
        run: zip -qq -r ./source.zip .
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./source.zip s3://kbobot/source.zip
      - name: Deploy
        run: aws deploy create-deployment
          --application-name kbobot
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name node-deploy-pipe
          --s3-location bucket=kbobot,bundleType=zip
